myproject/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField("Post")

myproject/blog_posts/views.py
from flask import render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user,login_required
from myproject import db
from myproject.models import BlogPost
from myproject.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id
                             )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)


# int: makes sure that the blog_post_id gets passed as in integer
# instead of a string so we can look it up later.
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    # grab the requested blog post by id number or return 404
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post
    )

@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Update',
                           form=form)


@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))

myproject/core/views.py
from flask import render_template, request, Blueprint
from myproject.models import BlogPost

core = Blueprint('core', __name__)


@core.route('/')
def index():
    '''
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)
    return render_template('index.html',blog_posts=blog_posts)

@core.route('/info')
def info():
    '''
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    '''
    return render_template('info.html')

myproject/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myproject import db
from myproject.models import User, BlogPost
from myproject.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from myproject.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)
# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


# login
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Logged in Successful')
            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

# account
@users.route('/account', methods=['GET', "POST"])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    profile_image = url_for(
        'static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(
        BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blogs.html', blog_posts=blog_posts, user=user)

myproject/templates/account.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>Welcome {{ current_user.username }}</h1>
  <img
    style="width:200px"
    src="{{url_for('static', filename='profile_pics/'+current_user.profile_image)}}"
    alt="image"
  />
  <form method="post" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    {{ form.email.label }}{{ form.email() }} <br />
    {{ form.username.label }}{{ form.username() }} <br />
    {{ form.picture.label }}{{ form.picture() }} <br />
    {{ form.submit(class="btn btn-success") }}
  </form>
</div>
{% endblock content %}

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="steve" content="First Flask Template" />
    <title>First Template</title>
    <!-- Bootstrap core CSS -->
    <link
      href="{{url_for('static', filename='css/bootstrap.min.css')}}"
      rel="stylesheet"
    />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link
      href="{{url_for('static', filename='css/main.css')}}"
      rel="stylesheet"
    />
  </head>
  <body>
    {% include 'navbar.html' %}

    <main role="main" class="container-fluid">
      {% block content %} {% endblock content %}
    </main>
    <script src="{{url_for('static', filename='js/jquery-3.4.1.min.js')}}"></script>
    <script>
      window.jQuery ||
        document.write(
          '<script src="{{url_for('static', filename='js/jquery-3.4.1.min.js')}}">')</script
    >;<script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
  </body>
</html>

myproject/templates/blog_post.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{ post.author.username }}</h2>
  <h3>Published: {{ post.date.strftime("%B %d, %Y") }}</h3>
  <p>{{ post.text }}</p>

  {% if post.author == current_user %}
  <div>
    <a href="{{url_for('blog_posts.update',blog_post_id=post.id)}}">Update</a>
    <button
      type="button"
      class="btn btn-danger"
      data-toggle="modal"
      data-target="#del_modal"
    >
      Delete
    </button>
  </div>

  {% endif %}
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post?</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Cancel
        </button>

        <form
          action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}"
          method="post"
        >
          <input class="btn btn-danger" type="submit" value="Delete" />
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

myproject/templates/create_post.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <form class="form-group" method="POST">
    {{ form.hidden_tag() }}

    <div class="form-group">
      {{form.title.label(class="form-control-label")}}
      {{form.title(class="form-control form-control-lg")}}
    </div>
    <div class="form-group">
      {{form.text.label(class="form-control-label")}}
      {{form.text(class="form-control form-control-lg")}}
    </div>
    <div class="form-group">
      {{form.submit(class="btn btn-outline-info")}}
    </div>
  </form>
</div>
{% endblock %}

myproject/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Puppy Company Blog</h1>
    <p>Welcome to Our Company's Blog Page</p>
  </div>

  <div class="container">

    {# Go through each blog post #}
    {% for post in blog_posts.items %}

    <div class="card" >

      <div class="card-body">


        <h2><a class="card-title" href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
      </div>
    </div>

   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
    </nav>




{% endblock %}

myproject/templates/info.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>
    Infor about our company
  </h1>
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi repudiandae
    nemo dolore. Enim eligendi tempora beatae quaerat nobis repudiandae
    necessitatibus laborum voluptates fugit, porro dicta! Iure quis deserunt
    incidunt officiis!
  </p>
</div>
{% endblock content %}

myproject/templates/login.html
{% extends "base.html" %} {% block content %}
<form method="POST">
  {{ form.hidden_tag() }}
  {{ form.email.label }}{{ form.email }}<br />
  {{ form.password.label }}{{ form.password }}<br />
  {{ form.submit() }}
</form>
{% endblock %}

myproject/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('core.index') }}">Puppy</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarsExampleDefault"
    aria-controls="navbarsExampleDefault"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if url == 'index' %} active {% endif %}">
        <a class="nav-link" href="{{ url_for('core.index') }}"
          >Home <span class="sr-only">(current)</span></a
        >
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{{ url_for('core.info') }}">About</a>
      </li>
      {% if current_user.is_authenticated %}
      <li class="nav-item ">
        <a class="nav-link" href="{{ url_for('users.logout') }}">logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('blog_posts.create_post') }}"
          >Create Post</a
        >
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.login') }}">login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.register') }}">register</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

myproject/templates/register.html
{% extends 'base.html' %} {% block content %}
<form method="post">
  {{ form.hidden_tag() }}
  {{ form.email.label }}{{ form.email() }} <br />
  {{ form.password.label }}{{ form.password() }} <br />
  {{ form.password_confirm.label }}{{ form.password() }} <br />
  {{ form.submit(class="btn btn-success") }}
</form>
{% endblock content %}

myproject/templates/user_blogs.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="jumbotron">
    <div align="center">
      <h1>Welcome to the page for {{ user.username }}</h1>
      <img
        src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}"
      />
    </div>
  </div>

  {% for post in  blog_posts.items  %}
  <h2>
    <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{
      post.title
    }}</a>
  </h2>
  Written By:
  <a href="{{url_for('users.user_post',username=post.author.username)}}">{{
    post.author.username
  }}</a>
  <p class="text-muted">Published on: {{ post.date.strftime("%Y-%m-%d") }}</p>
  <br />
  <p>{{ post.text }}</p>
  <br />
  {% endfor %}
</div>

<nav aria-label="Page Navigation example">
  <ul class="pagination justify-content-center">
    {% for page_num in
    blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)
    %} {% if blog_posts.page == page_num %}
    <li class="page-item disabled">
      <a
        class="page-link"
        href="{{url_for('users.user_posts',username=user.username,page=page_num)}}"
        >{{ page_num }}</a
      >
    </li>
    {% else %}
    <li class="page-item">
      <a
        class="page-link"
        href="{{url_for('users.user_posts',username=user.username,page=page_num)}}"
        >{{ page_num }}</a
      >
    </li>
    {% endif %} {% endfor %}
  </ul>
</nav>

{% endblock %}